/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "ifxkryalmmxlclxpipww"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlmeGtyeWFsbW14bGNseHBpcHd3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjkxMjQ3NjAsImV4cCI6MjA4NDcwMDc2MH0.q-unil7-oq0kS_u54HwpCpf3EZ7NtO7z-cynnTi-T6s"